require('packer-config')
require('settings')
require('mappings')
require('colorschemes-config.nightfox')
-- require('colorschemes-config.catppuccin')
-- require('colorschemes-config.nord')
require('nvim-tree-config')
require('lualine-config')
require('barbar-config')
require('nvim-treesitter-config')
require('nvim-lsp-config.auto-lsp-installer')
require('nvim-lsp-config.neovim-cmp')
require('autopairs-config')
require('telescope-config')
require('dashboard-config').config()
