require('packer-setup')
require('settings')
require('mappings')
require('plugins.colorschemes.nightfox')
require('plugins.notify')
require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.barbar-config')
require('plugins.treesitter')
require('plugins.autopairs')
require('plugins.telescope')
require('plugins.neovim-cmp')
require('plugins.lspconfig')
require('plugins.dashboard').config()
--require('colorschemes-config.nightfox')
-- require('colorscheme
-- s-config.catppuccin')
-- require('colorschemes-config.nord')
--require('nvim-tree-config')
--require('lualine-config')
--require('barbar-config')
--require('nvim-treesitter-config')
--require('nvim-lsp-config.auto-lsp-installer')
--require('nvim-lsp-config.neovim-cmp')
--require('autopairs-config')
--require('telescope-config')
--require('dashboard-config').config()
